AWSTemplateFormatVersion: 2010-09-09
Description: "CloudFormation distribution used to serve static files"

Parameters:
  SourceBucketName:
    Type: String
    Description: "The name for the bucket where the source for aristotle-labs is stored"

  AccessLogBucket:
    Type: String
    Description: "Bucket to logs s3 access events to"

  DomainName:
    Type: String
    Description: "Domain name to use for distribution"

  CertARN:
    Type: String
    Description: "ARN of acm certificate for domain (cloudfront requires a us-east-1 cert)"

Resources:
  LabsCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SourceBucketName
      LoggingConfiguration:
          DestinationBucketName: !Ref AccessLogBucket
          LogFilePrefix: !Sub "${AWS::StackName}/"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  DistributionAccessBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LabsCodeBucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Principal:
              CanonicalUser: !GetAtt OriginAccessId.S3CanonicalUserId
            Resource: !Sub "${LabsCodeBucket.Arn}/*"

  # A special user for the CloudFormation distribution, allowing access
  # to the S3 bucket to be restricted
  OriginAccessId:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "Identity for the Aristotle Labs Bucket"

  LabsDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: True
        DefaultRootObject: 'index.html'
        Aliases:
          - !Ref DomainName
        DefaultCacheBehavior:
          Compress: True
          ViewerProtocolPolicy: 'redirect-to-https'
          TargetOriginId: 'Aristotle Labs Static Bucket'
          ForwardedValues:
            QueryString: True
        Origins:
          - DomainName: !GetAtt LabsCodeBucket.DomainName
            Id: 'Aristotle Labs Static Bucket'
            S3OriginConfig:
              # The CloudFront origin access identity to associate
              # with the origin
              OriginAccessIdentity:
                !Join
                - ''
                - - 'origin-access-identity/cloudfront/'
                  - !Ref OriginAccessId
        PriceClass: "PriceClass_All"
        ViewerCertificate:
          AcmCertificateArn: !Ref CertARN
          MinimumProtocolVersion: "TLSv1.2_2018"
          SslSupportMethod: "sni-only"

Outputs:
  SourceBucketArn:
    Description: "The ARN of the code bucket for aristotle-labs source code"
    Value: !GetAtt LabsCodeBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SourceBucketArn"

  SourceBucketName:
    Description: "The name of the S3 bucket where the webpack bundle of aristotle-labs code lives"
    Value: !Ref LabsCodeBucket
    Export:
      Name: !Sub "${AWS::StackName}-SourceBucketName"

  DistributionId:
    Description: "Id of cloudfront distribution"
    Value: !Ref LabsDistribution
    Export:
      Name: !Sub "${AWS::StackName}-DistributionId"
